services:
  - type: web
    name: devshowcase-api
    runtime: docker
    plan: free
    healthCheckPath: /v3/api-docs
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: devshowcase-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: devshowcase-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: devshowcase-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: devshowcase-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: devshowcase-db
          property: password

databases:
  - name: devshowcase-db
    plan: free
