server.port=${PORT:10000}

# Configuração explícita para evitar o erro de Dialect do Hibernate
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Documentação Swagger
springdoc.swagger-ui.path=/swagger-ui.html
